### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by CouldBeThis** [Moarram/headline-zsh-theme#2]
Stumbled on this repo while websearching for documentation. Was not seeking for it.  Looks like it's a wee baby theme just a few days old. I think you are onto something here, it's great!

Compared to `powerline` and other `zsh` themes this compares very favorably for my tastes. It does not skimp on displaying useful information, yet also copes well when squeezed into a narrow terminal window. Those are often mutually exclusive. I think the visual balance is fab too. The colors are enough to break it up so you can easily tell what's going on and it looks nice, but not so much that it's like shouting to get your attention. And lastly there is _not_ an excess of whitespace, taking up my monitor with nothing and requiring excessive scrolling back to see what just happened. Also IMHO a lot of the whitespace-heavy themes can feel off kilter. I think this is solid and efficient. 

But this is a text box for problems not compliments. So; back to business. 

I strongly agree with the suggestion made in #1 the repo be renamed. When cloned, it creates a folder called `zsh-theme` which is confusing and way less memorable than is deserved.   I think the sooner you rename it, the better, because trying to rename things after they already popped off is a huge pain in the ass. Unless you plan to dominate all the others to become "_The_ Theme". you do you.

**Comment by Moarram** [comment]
Thank you for the compliments! Yes I agree about the repo name being too vague. Should I name the repo `moarram.zsh-theme`? I'm too picky with naming things... do you have any better ideas?

**Comment by Moarram** [comment]
@CouldBeThis The new name is "Headline"

**Comment by CouldBeThis** [comment]
great name!
